name: my infra pipeline

on:
    push:
        branches:
            - main
            - stage
    pull_request:
        branches:
            - manin    
jobs:
    terraform:
        name: terraform plan and validate
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
                working-directory: ./terraform

        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: prepare and install terraform
              uses: hashicorp/setup-terraform@v3              

            - name: fmt the code
              run: terraform fmt

            - name: initialize terraform
              id: init
              run: terraform init --backend-config="bucket=gitopstf"          

            - name: validate the code
              id: validate
              run: terraform validate


